Controllers/AdminUserInfoController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Mvc.Rendering;
//using Microsoft.EntityFrameworkCore;
//using TieTheKnot.Data;
//using TieTheKnot.Models;

//namespace TieTheKnot.Controllers
//{
//    public class AdminUserInfoController : Controller
//    {
//        private readonly ApplicationDbContext _context;

//        public AdminUserInfoController(ApplicationDbContext context)
//        {
//            _context = context;
//        }

//        // GET: AdminUserInfo
//        public async Task<IActionResult> Index()
//        {
//              return _context.UserInfo != null ? 
//                          View(await _context.UserInfo.ToListAsync()) :
//                          Problem("Entity set 'ApplicationDbContext.UserInfo'  is null.");
//        }

//        // GET: AdminUserInfo/Details/5
//        public async Task<IActionResult> Details(long? id)
//        {
//            if (id == null || _context.UserInfo == null)
//            {
//                return NotFound();
//            }

//            var userInfo = await _context.UserInfo
//                .FirstOrDefaultAsync(m => m.Id == id);
//            if (userInfo == null)
//            {
//                return NotFound();
//            }

//            return View(userInfo);
//        }

//        // GET: AdminUserInfo/Create
//        public IActionResult Create()
//        {
//            return View();
//        }

//        // POST: AdminUserInfo/Create
//        // To protect from overposting attacks, enable the specific properties you want to bind to.
//        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Create([Bind("Id,UserName,CateringServices,Decoration,City,PhotographyServices,WeddingDate,WeddingVenue")] UserInfo userInfo)
//        {
//            if (ModelState.IsValid)
//            {
//                _context.Add(userInfo);
//                await _context.SaveChangesAsync();
//                return RedirectToAction(nameof(Index));
//            }
//            return View(userInfo);
//        }

//        // GET: AdminUserInfo/Edit/5
//        public async Task<IActionResult> Edit(long? id)
//        {
//            if (id == null || _context.UserInfo == null)
//            {
//                return NotFound();
//            }

//            var userInfo = await _context.UserInfo.FindAsync(id);
//            if (userInfo == null)
//            {
//                return NotFound();
//            }
//            return View(userInfo);
//        }

//        // POST: AdminUserInfo/Edit/5
//        // To protect from overposting attacks, enable the specific properties you want to bind to.
//        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Edit(long id, [Bind("Id,UserName,CateringServices,Decoration,City,PhotographyServices,WeddingDate,WeddingVenue")] UserInfo userInfo)
//        {
//            if (id != userInfo.Id)
//            {
//                return NotFound();
//            }

//            if (ModelState.IsValid)
//            {
//                try
//                {
//                    _context.Update(userInfo);
//                    await _context.SaveChangesAsync();
//                }
//                catch (DbUpdateConcurrencyException)
//                {
//                    if (!UserInfoExists(userInfo.Id))
//                    {
//                        return NotFound();
//                    }
//                    else
//                    {
//                        throw;
//                    }
//                }
//                return RedirectToAction(nameof(Index));
//            }
//            return View(userInfo);
//        }

//        // GET: AdminUserInfo/Delete/5
//        public async Task<IActionResult> Delete(long? id)
//        {
//            if (id == null || _context.UserInfo == null)
//            {
//                return NotFound();
//            }

//            var userInfo = await _context.UserInfo
//                .FirstOrDefaultAsync(m => m.Id == id);
//            if (userInfo == null)
//            {
//                return NotFound();
//            }

//            return View(userInfo);
//        }

//        // POST: AdminUserInfo/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> DeleteConfirmed(long id)
//        {
//            if (_context.UserInfo == null)
//            {
//                return Problem("Entity set 'ApplicationDbContext.UserInfo'  is null.");
//            }
//            var userInfo = await _context.UserInfo.FindAsync(id);
//            if (userInfo != null)
//            {
//                _context.UserInfo.Remove(userInfo);
//            }

//            await _context.SaveChangesAsync();
//            return RedirectToAction(nameof(Index));
//        }

//        private bool UserInfoExists(long id)
//        {
//          return (_context.UserInfo?.Any(e => e.Id == id)).GetValueOrDefault();
//        }
//    }
//}



using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TieTheKnot.Data;
using TieTheKnot.Models;

namespace TieTheKnot.Controllers
{
    public class AdminUserInfoController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminUserInfoController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AdminUserInfo
        public async Task<IActionResult> Index(string searchString)
        {
            IQueryable<UserInfo> userInfo = _context.UserInfo;

            if (!string.IsNullOrEmpty(searchString))
            {
                userInfo = userInfo.Where(u => u.UserName.Contains(searchString));
            }

            return View(await userInfo.ToListAsync());
        }

        // GET: AdminUserInfo/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.UserInfo == null)
            {
                return NotFound();
            }

            var userInfo = await _context.UserInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userInfo == null)
            {
                return NotFound();
            }

            return View(userInfo);
        }

        // GET: AdminUserInfo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminUserInfo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserName,CateringServices,Decoration,City,PhotographyServices,WeddingDate,WeddingVenue")] UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userInfo);
        }

        // GET: AdminUserInfo/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.UserInfo == null)
            {
                return NotFound();
            }

            var userInfo = await _context.UserInfo.FindAsync(id);
            if (userInfo == null)
            {
                return NotFound();
            }
            return View(userInfo);
        }

        // POST: AdminUserInfo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,UserName,CateringServices,Decoration,City,PhotographyServices,WeddingDate,WeddingVenue")] UserInfo userInfo)
        {
            if (id != userInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserInfoExists(userInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userInfo);
        }

        // GET: AdminUserInfo/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.UserInfo == null)
            {
                return NotFound();
            }

            var userInfo = await _context.UserInfo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userInfo == null)
            {
                return NotFound();
            }

            return View(userInfo);
        }

        // POST: AdminUserInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.UserInfo == null)
            {

Views/AdminUserInfo/Create.cshtml
@model TieTheKnot.Models.UserInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CateringServices" class="control-label"></label>
                <input asp-for="CateringServices" class="form-control" />
                <span asp-validation-for="CateringServices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Decoration" class="control-label"></label>
                <input asp-for="Decoration" class="form-control" />
                <span asp-validation-for="Decoration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotographyServices" class="control-label"></label>
                <input asp-for="PhotographyServices" class="form-control" />
                <span asp-validation-for="PhotographyServices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeddingDate" class="control-label"></label>
                <input asp-for="WeddingDate" class="form-control" />
                <span asp-validation-for="WeddingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeddingVenue" class="control-label"></label>
                <input asp-for="WeddingVenue" class="form-control" />
                <span asp-validation-for="WeddingVenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AdminUserInfo/Delete.cshtml
@model TieTheKnot.Models.UserInfo

@{
    ViewData["Title"] = "Delete";
}
<style>
    h1 {
        color: red;
        padding: 5px;
        display: inline-block;
    }

    h3 {
        color: red;
        padding-bottom: 5px;
    }
</style>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserInfo</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CateringServices)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CateringServices)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Decoration)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Decoration)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PhotographyServices)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhotographyServices)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WeddingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WeddingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WeddingVenue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WeddingVenue)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <br />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/AdminUserInfo/Details.cshtml
@model TieTheKnot.Models.UserInfo

@{
    ViewData["Title"] = "Details";
}

<style>
    /* Add your custom styles here */
    .details-container {
        max-width: 600px;
        margin: 0 auto;
    }

        .details-container h1 {
            text-align: center;
        }

        .details-container dl {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 16px;
        }

        .details-container dt, .details-container dd {
            padding: 8px;
            
        }

        .details-container a {
            display: block;
            margin-top: 16px;
            text-align: center;
        }
</style>

<div class="details-container">
    <h1>Details</h1>

    <div>
        <h4>UserInfo</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CateringServices)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CateringServices)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Decoration)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Decoration)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PhotographyServices)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PhotographyServices)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.WeddingDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeddingDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.WeddingVenue)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.WeddingVenue)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> 
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

Views/AdminUserInfo/Edit.cshtml
@model TieTheKnot.Models.UserInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CateringServices" class="control-label"></label>
                <input asp-for="CateringServices" class="form-control" />
                <span asp-validation-for="CateringServices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Decoration" class="control-label"></label>
                <input asp-for="Decoration" class="form-control" />
                <span asp-validation-for="Decoration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotographyServices" class="control-label"></label>
                <input asp-for="PhotographyServices" class="form-control" />
                <span asp-validation-for="PhotographyServices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeddingDate" class="control-label"></label>
                <input asp-for="WeddingDate" class="form-control" />
                <span asp-validation-for="WeddingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeddingVenue" class="control-label"></label>
                <input asp-for="WeddingVenue" class="form-control" />
                <span asp-validation-for="WeddingVenue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/AdminUserInfo/Index.cshtml
@model IEnumerable<TieTheKnot.Models.UserInfo>

@{
    ViewData["Title"] = "Index";
}

<style>
    /* Add your custom CSS styles here */
    .card {
        margin-bottom: 20px;
    }

    .card-header {
        background-color: #007bff;
        color: #fff;
    }
</style>

<h1>Index</h1>

<div class="row">
    <div class="col-md-6">
        <form class="d-flex" asp-action="Index" asp-controller="AdminUserInfo">
            <input name="searchString" class="form-control me-1" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-dark" type="submit">Search by name</button>
        </form>
    </div>

    <div class="col-md-6">
        <a asp-action="Index" class="text-dark">Back to full List</a>
    </div>
</div>

@if (Model.Any())
{
    foreach (var item in Model)
    {
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">@Html.DisplayFor(modelItem => item.UserName)</h5>
            </div>
            <div class="card-body">
                <p class="card-text">
                    <strong>Catering Services:</strong> @Html.DisplayFor(modelItem => item.CateringServices)<br />
                    <strong>Decoration:</strong> @Html.DisplayFor(modelItem => item.Decoration)<br />
                    <strong>City:</strong> @Html.DisplayFor(modelItem => item.City)<br />
                    <strong>Photography Services:</strong> @Html.DisplayFor(modelItem => item.PhotographyServices)<br />
                    <strong>Wedding Date:</strong> @Html.DisplayFor(modelItem => item.WeddingDate)<br />
                    <strong>Wedding Venue:</strong> @Html.DisplayFor(modelItem => item.WeddingVenue)<br />
                </p>
                <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                <a class="btn btn-success" asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger ml-2">Delete</a>
            </div>
        </div>
    }
}
else
{
    <p>No data available</p>
}